In [1]:
import numpy as np

In [2]:
range(10)

range(0, 10)

In [3]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
list(range(2.0,10.0))

TypeError: 'float' object cannot be interpreted as an integer

In [5]:
np.range(10)

AttributeError: module 'numpy' has no attribute 'range'

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(5,-4,-2)

array([ 5,  3,  1, -1, -3])

In [12]:
np.linspace(1,5,10) # includes both upper bound and lower bound

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [13]:
np.logspace(1,5,10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.zeros([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
np.zeros([3,4,5])

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [19]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
np.ones([3,4,5])

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [22]:
np.empty([2,3])

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [1.29061074e-306, 1.89146896e-307, 7.56571288e-307]])

In [25]:
a=np.eye(4)

In [26]:
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [27]:
a.shape

(4, 4)

In [29]:
a1=np.random.randn(3,4)

In [30]:
a1

array([[-0.17804268,  2.4081464 , -0.05867384, -0.47445131],
       [ 0.02432083,  1.55628188,  1.22744429,  1.11826931],
       [-2.32938517,  0.08837414, -0.43390799,  0.78919   ]])

In [31]:
a2=np.random.rand(3,4)

In [32]:
a2

array([[0.89452273, 0.77813851, 0.91082393, 0.36101142],
       [0.46752248, 0.17669579, 0.9468811 , 0.39905589],
       [0.06947535, 0.63642448, 0.5912194 , 0.32536611]])

In [33]:
import pandas as pd

In [34]:
a2

array([[0.89452273, 0.77813851, 0.91082393, 0.36101142],
       [0.46752248, 0.17669579, 0.9468811 , 0.39905589],
       [0.06947535, 0.63642448, 0.5912194 , 0.32536611]])

In [35]:
a1

array([[-0.17804268,  2.4081464 , -0.05867384, -0.47445131],
       [ 0.02432083,  1.55628188,  1.22744429,  1.11826931],
       [-2.32938517,  0.08837414, -0.43390799,  0.78919   ]])

In [36]:
a1[1][1]

1.5562818776626695

In [37]:
a1[1:,2:]

array([[ 1.22744429,  1.11826931],
       [-0.43390799,  0.78919   ]])

In [39]:
a1[1:,3:]

array([[1.11826931],
       [0.78919   ]])

In [40]:
a1

array([[-0.17804268,  2.4081464 , -0.05867384, -0.47445131],
       [ 0.02432083,  1.55628188,  1.22744429,  1.11826931],
       [-2.32938517,  0.08837414, -0.43390799,  0.78919   ]])

In [41]:
a1[1:,2:]

array([[ 1.22744429,  1.11826931],
       [-0.43390799,  0.78919   ]])

In [42]:
a1[1:,3:]

array([[1.11826931],
       [0.78919   ]])

In [43]:
m1 = np.random.randint(1,3 , (3,3))

In [46]:
m1

array([[1, 1, 2],
       [2, 2, 1],
       [2, 1, 2]])

In [47]:
m2

array([[2, 3, 2],
       [3, 3, 2],
       [3, 2, 3]])

In [44]:
m2 = np.random.randint(2,4 , (3,3))

In [45]:
m1*m2 # element wise multipilcation

array([[2, 3, 4],
       [6, 6, 2],
       [6, 2, 6]])

In [48]:
m1@m2 # matrix multiplication

array([[11, 10, 10],
       [13, 14, 11],
       [13, 13, 12]])

In [49]:
## applying power 
pow(m1,4)

array([[ 1,  1, 16],
       [16, 16,  1],
       [16,  1, 16]], dtype=int32)

In [50]:
np.sqrt(m1)

array([[1.        , 1.        , 1.41421356],
       [1.41421356, 1.41421356, 1.        ],
       [1.41421356, 1.        , 1.41421356]])

In [51]:
np.log10(m1)

array([[0.     , 0.     , 0.30103],
       [0.30103, 0.30103, 0.     ],
       [0.30103, 0.     , 0.30103]])

In [52]:
np.exp(m1)

array([[2.71828183, 2.71828183, 7.3890561 ],
       [7.3890561 , 7.3890561 , 2.71828183],
       [7.3890561 , 2.71828183, 7.3890561 ]])

In [53]:

m1**2

array([[1, 1, 4],
       [4, 4, 1],
       [4, 1, 4]])

In [54]:
m1**4

array([[ 1,  1, 16],
       [16, 16,  1],
       [16,  1, 16]], dtype=int32)