In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5]

In [3]:
type(l)

list

In [4]:
np.array(l)

array([1, 2, 3, 4, 5])

In [5]:
type(np.array(1))

numpy.ndarray

In [6]:
arr1=np.array(l)

In [7]:
arr1

array([1, 2, 3, 4, 5])

In [8]:
a1 = np.array([[1,2,3] , [3,4,5]])

In [9]:
a1

array([[1, 2, 3],
       [3, 4, 5]])

In [10]:
a1.ndim

2

In [11]:
a2 = np.array([[[1,2,3] , [4,.5,6]]])

In [12]:
a2

array([[[1. , 2. , 3. ],
        [4. , 0.5, 6. ]]])

In [13]:
a2.ndim

3

In [14]:
a3 = np.array([[[1,2,3] , [4,.5,6]],[[1,2,3] , [4,.5,6]],[[1,2,3] , [4,.5,6]]])

In [15]:
a3

array([[[1. , 2. , 3. ],
        [4. , 0.5, 6. ]],

       [[1. , 2. , 3. ],
        [4. , 0.5, 6. ]],

       [[1. , 2. , 3. ],
        [4. , 0.5, 6. ]]])

In [16]:
a3[2][0][2]

3.0

In [17]:
a3.ndim

3

In [19]:
l = [1,2,3,4]

In [20]:
a = np.asarray(l)

In [21]:
a

array([1, 2, 3, 4])

In [22]:
m = np.matrix(l)

In [23]:
m

matrix([[1, 2, 3, 4]])

In [24]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [24]:
np.asanyarray(a)

array([1, 2, 3, 4])

In [25]:
np.asanyarray(m)

matrix([[1, 2, 3, 4]])

In [25]:
a

array([1, 2, 3, 4])

In [26]:
a1=a

In [27]:
a1

array([1, 2, 3, 4])

In [28]:
a

array([1, 2, 3, 4])

In [29]:
a[0] = 10

In [30]:
a

array([10,  2,  3,  4])

In [31]:
a1

array([10,  2,  3,  4])

In [32]:
a1[3] = 50

In [33]:
a1

array([10,  2,  3, 50])

In [34]:
a

array([10,  2,  3, 50])

In [35]:
a2 = np.copy(a)

In [36]:
a

array([10,  2,  3, 50])

In [37]:
a2

array([10,  2,  3, 50])

In [38]:
a2[2] = 30

In [39]:
a2

array([10,  2, 30, 50])

In [40]:
a

array([10,  2,  3, 50])

In [41]:
np.fromfunction(lambda i,j:i==j,(3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [42]:
np.random.rand(2,3,3)

array([[[0.73114584, 0.59363206, 0.81773884],
        [0.82276121, 0.29227143, 0.73139913],
        [0.92934324, 0.27988097, 0.74189629]],

       [[0.07077319, 0.79613626, 0.02303127],
        [0.6922341 , 0.25130284, 0.75937179],
        [0.23824443, 0.20180877, 0.71034272]]])

In [43]:
np.random.rand(2,3,2,2)

array([[[[0.73333948, 0.23502697],
         [0.79673033, 0.50811402]],

        [[0.09321505, 0.72120367],
         [0.25787406, 0.8347513 ]],

        [[0.73278258, 0.65042011],
         [0.68611491, 0.86114496]]],


       [[[0.94272382, 0.91201251],
         [0.01375633, 0.99983135]],

        [[0.47381277, 0.40276622],
         [0.61574208, 0.7576548 ]],

        [[0.39712115, 0.11490257],
         [0.7111383 , 0.18152101]]]])

In [44]:

np.random.rand(3,4,5)

array([[[0.80145288, 0.41719132, 0.99544995, 0.02669679, 0.48004507],
        [0.36716441, 0.86995458, 0.57629054, 0.70563419, 0.06987699],
        [0.68956881, 0.15185595, 0.34909463, 0.88426562, 0.26311106],
        [0.56870112, 0.54932399, 0.57056131, 0.00778401, 0.95312039]],

       [[0.67414009, 0.37606745, 0.4772875 , 0.18997852, 0.47740667],
        [0.97675415, 0.46335657, 0.01955182, 0.54188171, 0.78604131],
        [0.66208028, 0.75307306, 0.29362243, 0.72501772, 0.28918624],
        [0.27665038, 0.68739335, 0.62648213, 0.2163563 , 0.30206399]],

       [[0.66213533, 0.37573462, 0.3375533 , 0.69431975, 0.90698483],
        [0.54625912, 0.49448241, 0.62503425, 0.4474909 , 0.75596616],
        [0.72559975, 0.20925257, 0.6456189 , 0.4570185 , 0.79885653],
        [0.96575207, 0.94900272, 0.88447697, 0.64170105, 0.78095345]]])

In [45]:
d = np.random.randn(3,4)

In [46]:
d

array([[-0.29857077,  0.71495332,  2.28800423,  0.72782326],
       [ 1.55496353, -0.61875662, -0.79487992, -0.0759738 ],
       [-0.02369437,  0.05833709, -0.9755007 , -1.11052884]])

In [48]:
import pandas as pd

In [49]:
pd.DataFrame(d)


0         1         2         3
0 -0.298571  0.714953  2.288004  0.727823
1  1.554964 -0.618757 -0.794880 -0.075974
2 -0.023694  0.058337 -0.975501 -1.110529

In [50]:
d1=np.random.randint(0,10,(4,4,2))

In [51]:
d1

array([[[0, 6],
        [5, 1],
        [6, 2],
        [5, 9]],

       [[4, 8],
        [7, 6],
        [1, 5],
        [7, 8]],

       [[9, 7],
        [3, 5],
        [3, 4],
        [2, 1]],

       [[5, 2],
        [1, 0],
        [0, 3],
        [5, 3]]])

In [52]:
d1.reshape(16,2)

array([[0, 6],
       [5, 1],
       [6, 2],
       [5, 9],
       [4, 8],
       [7, 6],
       [1, 5],
       [7, 8],
       [9, 7],
       [3, 5],
       [3, 4],
       [2, 1],
       [5, 2],
       [1, 0],
       [0, 3],
       [5, 3]])

In [53]:
d1.reshape(8,4)

array([[0, 6, 5, 1],
       [6, 2, 5, 9],
       [4, 8, 7, 6],
       [1, 5, 7, 8],
       [9, 7, 3, 5],
       [3, 4, 2, 1],
       [5, 2, 1, 0],
       [0, 3, 5, 3]])

In [54]:
d1.reshape(4,4,2)

array([[[0, 6],
        [5, 1],
        [6, 2],
        [5, 9]],

       [[4, 8],
        [7, 6],
        [1, 5],
        [7, 8]],

       [[9, 7],
        [3, 5],
        [3, 4],
        [2, 1]],

       [[5, 2],
        [1, 0],
        [0, 3],
        [5, 3]]])